'use client'
import { useMemo, useState } from 'react'
import { masterCategories, masterProducts, masterSuppliers, formatRupiah, type MasterProduct } from './master-data-types'

type Tab = 'Produk' | 'Kategori' | 'Supplier' | 'Satuan'
export function MasterDataPage() {
  const [tab, setTab] = useState<Tab>('Produk')
  const [products, setProducts] = useState(masterProducts)
  const [query, setQuery] = useState('')
  const activeCount = products.filter((p) => p.active).length
  const filtered = useMemo(() => products.filter((p) => `${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())), [products, query])
  const toggle = (id: string) => setProducts((items) => items.map((p) => p.id === id ? { ...p, active: !p.active } : p))
  const addProduct = () => {
    const next: MasterProduct = { id: `product-${Date.now()}`, sku: `NEW-${products.length + 1}`, name: 'Produk baru', genericName: 'Produk baru', strength: '-', barcode: '', categoryId: masterCategories[0].id, supplierId: masterSuppliers[0].id, baseUnit: 'Tablet', units: [{ label: 'Tablet', price: 0, conversionFactor: 1 }], purchasePrice: 0, price: 0, availableStock: 0, minimumStock: 0, active: true }
    setProducts((items) => [next, ...items])
  }
  return <main className="master-page"><header className="master-header"><div><p className="eyebrow">Operasional apotek</p><h1>Data master</h1><p>Kelola produk, kategori, supplier, dan satuan penjualan dari satu tempat.</p></div><button className="master-primary" onClick={addProduct}>Tambah produk</button></header><section className="master-summary"><strong>{activeCount}</strong><span>produk aktif di kasir</span><span className="master-summary-dot" /> <span>{products.length} total produk</span></section><nav className="master-tabs" aria-label="Data master"><div>{(['Produk', 'Kategori', 'Supplier', 'Satuan'] as Tab[]).map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div></nav>{tab === 'Produk' ? <section className="master-panel"><div className="master-panel-head"><div><h2>Produk</h2><p>Produk aktif dapat langsung digunakan di kasir.</p></div><input aria-label="Cari produk" placeholder="Cari nama atau SKU" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="master-table-wrap"><table><thead><tr><th>Produk</th><th>Kategori</th><th>Supplier</th><th>Satuan</th><th>Harga jual</th><th>Status</th><th /></tr></thead><tbody>{filtered.map((product) => <tr key={product.id}><td><strong>{product.name}</strong><small>{product.sku}</small></td><td>{masterCategories.find((c) => c.id === product.categoryId)?.name}</td><td>{masterSuppliers.find((s) => s.id === product.supplierId)?.name}</td><td>{product.units.map((u) => u.label).join(' / ')}</td><td>{formatRupiah(product.price)}</td><td><span className={`master-status ${product.active ? 'on' : 'off'}`}>{product.active ? 'Aktif' : 'Nonaktif'}</span></td><td><button className="master-action" onClick={() => toggle(product.id)}>{product.active ? 'Nonaktifkan' : 'Aktifkan'}</button></td></tr>)}</tbody></table></div></section> : <section className="master-panel"><div className="master-panel-head"><div><h2>{tab}</h2><p>Referensi yang dipakai oleh data produk.</p></div></div><div className="master-reference-grid">{tab === 'Kategori' && masterCategories.map((item) => <article key={item.id}><strong>{item.name}</strong><span>{products.filter((p) => p.categoryId === item.id).length} produk</span></article>)}{tab === 'Supplier' && masterSuppliers.map((item) => <article key={item.id}><strong>{item.name}</strong><span>{item.contact}</span></article>)}{tab === 'Satuan' && ['Tablet', 'Strip', 'Box', 'Botol', 'Vial'].map((item) => <article key={item}><strong>{item}</strong><span>Satuan penjualan</span></article>)}</div></section>}</main>
}
